version: '3.8'

services:
    # Backend Service
    backend:
        build: ./backend
        container_name: queueless-backend
        ports:
            - '8080:8080'
        environment:
            - PORT=8080
            - MONGO_URI=${MONGO_URI}
        restart: unless-stopped
        networks:
            - queueless-network

    # Frontend Service
    frontend:
        build: ./frontend
        container_name: queueless-frontend
        ports:
            - '80:80'
        depends_on:
            - backend
        restart: unless-stopped
        networks:
            - queueless-network

networks:
    queueless-network:
        driver: bridge
